from tkinter import *
import insert
def new_trailer():
    newTrailerForm = Tk()
    newTrailerForm.title('Новый прицеп')
    label = Label(newTrailerForm, text='Добавление нового прицепа', fg='#909')
    label.grid(row=0, column=1)
    labelModel = Label(newTrailerForm, text='Модель Прицепа')
    labelModel.grid(row=1, column=0)
    textModel = Entry(newTrailerForm)
    textModel.grid(row=1, column=1)
    labelType=Label(newTrailerForm,text = 'Тип трейлера')
    labelType.grid(row=2,column=0)
    textType = Entry(newTrailerForm)
    textType.grid(row=2, column=1)
    labelTonnage = Label(newTrailerForm, text='Грузоподъемность (т)')
    labelTonnage.grid(row=3, column=0)
    textTonnage = Entry(newTrailerForm)
    textTonnage.grid(row=3, column=1)
    labelGosNumber = Label(newTrailerForm, text='ГосНомер')
    labelGosNumber.grid(row=4, column=0)
    textNumber = Entry(newTrailerForm)
    textNumber.grid(row=4, column=1)
    labelCost = Label(newTrailerForm, text='Стоимость (р)')
    labelCost.grid(row=5, column=0)
    textCost = Entry(newTrailerForm)
    textCost.grid(row=5, column=1)
    AddButton = Button(newTrailerForm, text='Добавить', command=lambda : insert.insert_trailer(textModel.get(), textType.get(), textTonnage.get(), textNumber.get(), textCost.get()))
    AddButton.grid(row=6, column=1)